### ISSUE TITLE
How to specify which submodules of an external to check out

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [bandre-ucar/manage_externals#168]
### Summary of Issue:

I've looked through the documentation, open issues, closed issues, for information about using the `externals` and `from_submodule` options for the configuration file and still cannot figure out how to do what I need.   I have an external defined in my `Externals.cfg` file that contains two submodules.  I need to clone that external such that one of the git submodules is checked out, and the other one is not.  I cannot modify the repository of that external.  For example,

I have an `Externals.cfg` file with:

```
[foo]
protocol = git
repo_url = https://github.com/foo.git
# Specify either a branch name or a hash but not both.
hash = de987e08
local_path = src/foo
required = True
```

But, `foo`, which does not have a `Externals.cfg` file, contains two git submodules:
```
[submodule "bar"]
	path = src/bar
	url = https://github.com/bar
[submodule "baz"]
	path = src/baz
	url = https://github.com/baz
```

When I run `checkout_externals` at the top level, I need it to clone `foo` such that the `bar` submodule is checked out, but the `baz` submodule is not.

How do I configure `Externals.cfg` to do that, keeping in mind that no changes to the `foo` repository are allowed?

### Expected behavior and actual behavior:

Expected behavior is complete control over which submodules of an external get checked out without modifying the repositories of the externals.  It seems that `externals=None` turns them off, but I don't see any way to specify specific submodules to check out.  The documentation suggests there is a way to do it with `from_submodule`, but my reading of that seems to indicate that it expects the specified submodule to be a submodule of the repo containing the `Externals.cfg` file, and that is not the case for my scenario. 

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):

I have a huge example, which I can provide if needed, but really I'm just asking a basic how-to, not reporting a bug.  So, I will provide it on request if the above isn't clear enough.

**Comment by gold2718** [comment]
Sorry about that.

If you do not specify any submodules in your Externals file, `checkout_externals` just initializes all the submodules.

However, if you _do_ include submodules, `checkout_externals` _should_ only check out the submodules you specify. For your case, if you specify the submodule you _do_ want checked out, `checkout_externals` should check out that one and not the other one.

Since you cannot add an Externals.cfg file to the external that has the submodules, you need to point to an Externals file you _can_ control. Perhaps something like: 
```
[foo]
protocol = git
repo_url = https://github.com/foo.git
# Specify either a branch name or a hash but not both.
hash = de987e08
local_path = src/foo
required = True
externals = ../../Externals_foo.cfg
```

Your Externals_foo.cfg file would contain the information for checking out the submodule you want. For instance, if you have submodules, subA and subB, you could have:
```
[externals_description]
schema_version = 1.1.0

[subA]
protocol = git
required = True
from_submodule = True
```
subA should be checked out but not subB.

Let me know if this does not work or you have other questions.

**Comment by christopherwharrop-noaa** [comment]
@gold2718 - Thank you!  One question about that path for `externals`.  From your example, it looks like the path for the `externals` field is relative to the destination directory (which is `src/foo` in this case) specified in the `local_path` field.  Am I understanding that correctly?

**Comment by gold2718** [comment]
Yes. My example put Externals_foo.cfg in the same directory as the main Externals.cfg file.

**Comment by christopherwharrop-noaa** [comment]
Thank you again.  I got it working using your example for a template.  Much appreciated.  This can be closed.
