### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by aerorahul** [bandre-ucar/manage_externals#199]
Can there be a release closer to the current date?
The last release was about 3 years ago.
We would like to use `manage_externals` as a standalone utility for several operational applications and the system administrators want to know why there hasn't been a release and if this project is actively developed or set for deprecation.

Any communication would be greatly helpful.

Thank you.

**Comment by billsacks** [comment]
This is still an actively developed and supported project. We stopped using GitHub releases, but we consider any commits on the `main` branch to be usable; the last commit was 5 days ago. Each commit on the main branch is also associated with a tag (https://github.com/ESMCI/manage_externals/tags). If it would help you for us to create a GitHub release from a recent tag, we can do that.

**Comment by billsacks** [comment]
Although we have high confidence in the latest version of main (manic-1.2.22), in order to provide a particularly well-vetted version, I checked the versions we have been using in CESM and CTSM for the last couple of months. CESM has been using manic-1.2.2 and CTSM manic-1.2.3; these two tags, which were made in January of this year, are effectively the same (the latter just has some updated documentation). Therefore, I am going to make a release from manic-1.2.3 and currently recommend that version for external use if you want a well-vetted version. Even though there have been many changes since that tag (thanks to @johnpaulalex ), they have been aimed at code cleanup and improvement of the unit and system tests so are not important for the use of manage_externals - though if you are going to make any changes, I would highly recommend starting with the latest version.
